update heading to utilize style props, new docs
raster-foundry/blasterjs pull request #186
Opened 2019-04-25 19:34 UTC by designmatty

## Overview
As part of our crusade to stop utilizing `Box` and `Text` on every component.

- `Heading` component no longer extends `Text`
- `Heading` utilizes Styled Props from `constants.js`
- New documentation pages
  - Style Props `/style-props`
  - Blaster Theme `/blaster-theme`
- Moved `Blaster` into Primitives menu

### Checklist

- [ ] Relevant documentation pages have been created or updated
- [ ] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible

Are there any of the following in this PR?

- [ ] Changes to the prop names or types of existing components
- [ ] Changes in intended behavior of existing component props
- [ ] Changes in the theme file's structure
- [ ] A required version bump to a non-dev dependency of the project

### Notes

There may be updates to docs or components that utilize Heading

## Testing Instructions

 * Ensure Heading works as before
 * Checkout `/style-props`
 * Checkout `/blaster-theme`
 * Make sure `Blaster` component docs exists at `/primitives/blaster`

2019-04-25 19:36 UTC, designmatty commented on docs/Home.mdx
> -order: -1
This is deprecated from docz

2019-04-25 19:38 UTC, designmatty commented on packages/core/theme/base.js
> +  `0 12px 17px 2px ${colors.gray900}20, 0 5px 22px 4px ${colors.gray900}20`
I made these changes because it was rendering oddly on the new Blaster Theme page.

2019-04-25 19:39 UTC, designmatty commented on packages/core/theme/components/breadcrumbs/index.js
> +    color: "gray500",
This is a quick fix that was missed in a previous PR. gray3 I no longer a color.

2019-04-29 19:33 UTC, lederer requested changes
Works as described.

See inline comment for a small requested change.

Great to see `Header` can now be styled using expected s-s props. Until now, `fontSize` (and maybe some other props?) could only be affected via the `tag` prop. 👍 

---

This doesn't necessarily need to be addressed in this PR, but I think the new docs pages add to our docs complexity debt. Eg…
- The Getting Started page mentions custom theming, then points to the Blaster component page for more info. 
- That Blaster component page, which is named for the entire library but is nested under Primitives, mostly covers theming. 
- But then there is a separate Blaster Theme page at the top level.
- And also a Style Props page, which kinda smells like its related to theming (bc "Style" props), but isn't really.

I think we can consider this PR's new docs pages as provisional – the objective being to get a draft of the key insights into the docs – and that we can follow up at some point soon with a docs refactoring.

2019-04-29 19:33 UTC, lederer commented on doczrc.js
> +    "Blaster Theme",
These new menu items should probably come after Getting Started.

2019-04-30 17:38 UTC, designmatty commented
I agree that the documentation is a bit all over. I wanted to get some preliminary documentation in there and once we have a settled approach I'd like to revise.

2019-04-30 17:47 UTC, lederer approved these changes

2019-04-30 17:48 UTC, merged