Dialog and button enhancements
raster-foundry/blasterjs pull request #215
Opened 2019-08-07 14:41 UTC by lederer

## Overview

Button
- Theme structure changed so default colors are now configured in `colors`.

Dialog
- Overlay color and opacity can now be themed or propped.
- Custom transitions can now be themed.
- z-index can now be propped.
- Focus ring color can now be themed, and has a default value.

### Checklist

- [x] Relevant documentation pages have been created or updated
- [ ] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible
- [ ] Relevant status has been updated on the status page

### Upgrade instructions

If there are any of the following in this PR, provide proper instructions on how to upgrade:

- [x] Changes to the prop names or types of existing components
- [ ] Changes in intended behavior of existing component props
- [x] Changes in the theme file's structure
- [ ] A required version bump to a non-dev dependency of the project

Button theme changes:
- `intents.colors.default` is now `base.colors.color`
- `base.colors.defaultBg` is now `base.colors.bg`
- `base.colors.defaultBorder` is now `base.colors.border`
- `base.colors.darkText` is now `base.colors.colorDark`
- `base.colors.lightText` is now `base.colors.colorLight`
- `base.hover.colors.defaultBg` is now `base.colors.bgHover`
- All other `base.hover.*` properties deprecated, and `base.hover` removed.

Dialog prop changes:
- `opacity` should now affect dialog opacity, not overlay opacity
- Added `overlayOpacity`
- Added `overlayColor`
- Added `zIndex`
- Deprecated: `portalClassName`, `overlayClassName`, `className`, `bodyOpenClassName`, `htmlOpenClassName`

Dialog theme changes:
- Added `colors.overlay`
- Added `colors.focus`
- Added `zIndices.zIndex`
- Added `opacities.overlay`
- Added `durations.closeTimeoutMS`
- Added `transitions.overlay.{base, afterOpen, beforeClose}`
- Added `transitions.dialog.{base, afterOpen, beforeClose}`

### Notes

Tweaked `replaceThemeRefs()` in utils.js to help prevent call stack errors.

Hard coded Dialog classnames, for simplicity.

Hid Field, ToggleField, and NavBar docs pages. They're to be deprecated.

## Testing Instructions

- Fiddle with new Button theme values. Confirm works as expected.
- Fiddle with new Dialog props and theme values. Confirm works as expected.

Closes #210 
Closes #211 
Closes #212 
Closes #213

2019-08-12 19:13 UTC, designmatty requested changes
Some weird alignment issues when you have more copy in the modal.

<img width="1552" alt="Screen Shot 2019-08-12 at 3 12 04 PM" src="https://user-images.githubusercontent.com/1928955/62891410-a44c4180-bd13-11e9-8a27-4346511c457a.png">

2019-08-12 19:13 UTC, designmatty commented on packages/core/components/dialog/index.js
> +      transition-function: ease-in-out;
should be `transition-timing-function`

2019-08-12 19:13 UTC, designmatty commented on packages/core/components/dialog/index.js
> +      transition-function: ease-in-out;
should be: `transition-timing-function`

2019-08-12 19:46 UTC, lederer commented
Nice catches. Ready for another look.

2019-08-22 21:23 UTC, designmatty approved these changes
Looks good now. Thanks for making those changes.

2019-08-26 14:17 UTC, merged