Feature/sml/range
raster-foundry/blasterjs pull request #216
Opened 2019-08-09 19:44 UTC by lederer

## Overview

Add `RangeInput` component, a wrapper for `<input type="range">".

X-browser styling is adapted from:
- https://brennaobrien.com/blog/2014/05/style-input-type-range-in-every-browser.html
- https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
- https://github.com/darlanrod/input-range-scss/blob/master/_inputrange.scss

### Checklist

- [x] Relevant documentation pages have been created or updated
- [ ] Description of PR is in an appropriate section of the changelog and grouped with similar changes if possible
- [ ] Relevant status has been updated on the status page

### Upgrade instructions

If there are any of the following in this PR, provide proper instructions on how to upgrade:

- [ ] Changes to the prop names or types of existing components
- [ ] Changes in intended behavior of existing component props
- [ ] Changes in the theme file's structure
- [ ] A required version bump to a non-dev dependency of the project

### Demo

![image](https://user-images.githubusercontent.com/128699/62804650-eaa76380-babb-11e9-9be0-cb2c18c4e4be.png)

### Notes

Also removed an unused import in Badge and tweaked the docs template to avoid errors in IE11.

## Testing Instructions

- Fiddle with the `RangeInput` docs page via props and theme

Closes #124 
Closes #202

2019-08-26 14:18 UTC, designmatty requested changes

2019-08-26 14:18 UTC, designmatty commented on packages/core/components/rangeInput/index.js
> +  &:disabled {
Unfortunately, some browsers (firefox I know for sure) will ignore these rules due to not recognizing the other browser prefixes in the comma-separated list. The fix here would be to have a separate `:disabled::-prefix-element {}` for each item in this list.

See this [StackOverflow](https://stackoverflow.com/questions/16982449/why-isnt-it-possible-to-combine-vendor-specific-pseudo-elements-classes-into-on?answertab=votes#tab-top) for a better explanation of why

2019-08-26 14:18 UTC, designmatty commented on packages/core/components/rangeInput/index.js
> +
Missing: 

```
&:focus::-moz-range-track {
    ${props => trackStyleFocus(props)}
}
```

2019-08-26 14:18 UTC, designmatty commented on packages/core/components/rangeInput/index.js
> +  &::-webkit-slider-runnable-track {
There is a discrepancy between moz and webkit in terms of box-sizing for this element.

Set this to `box-sizing: border-box;`

2019-08-26 14:18 UTC, designmatty commented on packages/core/components/rangeInput/index.js
> +  &::-moz-range-track {
There is a discrepancy between moz and webkit in terms of box-sizing for this element.

Set this to `box-sizing: border-box;`

2019-08-26 14:18 UTC, designmatty commented on packages/core/components/rangeInput/index.js
> +  type: "range"
Prevent overriding of type.

2019-08-26 14:18 UTC, designmatty commented on packages/core/components/rangeInput/index.mdx
> +    width,
Should this be `track` instead of width? I know while technically it's not the width of the track pseudo-element, in practice, it's essentially controlling the width of the track. This would also maintain a consistent naming convention across the theme.

2019-08-29 15:00 UTC, lederer commented
Ready for another look.

2019-08-29 20:25 UTC, designmatty approved these changes
Thanks for making those changes. Looks good.

2019-08-30 13:43 UTC, merged